# -*- coding: utf-8 -*-
#
# Mushroom documentation build configuration file, created by
# sphinx-quickstart on Wed Dec  6 10:51:04 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

from mushroom_rl import __version__
import datetime

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.intersphinx',
    'sphinx.ext.doctest',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = {'.rst': 'restructuredtext'}

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'MushroomRL'
current_year = datetime.datetime.now().year
copyright = f'2018-{current_year}, Carlo D\'Eramo, Davide Tateo'
author = 'Davide Tateo, Carlo D\'Eramo'


# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '.'.join(__version__.split('.')[:-1])

# The full version, including alpha/beta/rc tags.
release = __version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}

html_show_sourcelink = False
html_use_index = False

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'MushroomRLdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    'papersize': 'letterpaper',
    'pointsize': '10pt',
    'preamble': r'''
        \usepackage{seqsplit}
        \usepackage{microtype}
        \PassOptionsToPackage{hyphens}{url}
        \usepackage{newunicodechar}
        \newunicodechar{Λ}{\ensuremath{\Lambda}}
        \newunicodechar{λ}{\ensuremath{\lambda}}
        \usepackage{etoolbox}
        \makeatletter
        \@addtoreset{chapter}{part}
        \makeatother
    ''',
    'inputenc': '\\usepackage[utf8]{inputenc}',
    'makeindex': '\\usepackage[columns=1]{idxlayout}\\makeindex',
    'printindex': '\\def\\twocolumn[#1]{#1}\\footnotesize\\raggedright\\printindex',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
# 1. Promote your captions (Getting started, Tutorials, API) to LaTeX \part{} dividers
latex_toplevel_sectioning = "part"

# 2. Add True as the 6th tuple element
latex_documents = [
    (
        "latex_index",
        "MushroomRL.tex",
        "MushroomRL Documentation",
        "Davide Tateo, Carlo D'Eramo",
        "manual",
        False,
    ),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'mushroom_rl', u'MushroomRL Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'MushroomRL', u'MushroomRL Documentation',
     author, 'MushroomRL', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Options for autodoc ---------------------------------------------------

autodoc_member_order = 'bysource'
autodoc_mock_imports = ['scipy', 'sklearn', 'ale_py', 'pybullet', 'pybullet_data', 'pybullet_utils',
                        'dm_control', 'minigrid', 'mujoco', 'glfw', 'av', 'cv2',
                        'omni', 'pyqtgraph', 'PySide6']
add_module_names = False

autodoc_default_options = {
    'members': True,
    'show-inheritance': True,
}


# torch.nn.Module members that MushroomRL overrides without documenting. Autodoc would fall back to the inherited
# docstring, which documents PyTorch rather than MushroomRL.
_UNDOCUMENTED_MEMBERS = {'forward', 'extra_repr'}


# Interface methods documented only on their defining base class, not on every override.
_INTERFACE_ONLY = {'fit': 'Agent.', '_post_load': 'MushroomObject.'}


def skip(app, what, name, obj, skip, options):
    if name in _UNDOCUMENTED_MEMBERS:
        return True
    base = _INTERFACE_ONLY.get(name)
    if base is not None:
        return not getattr(obj, '__qualname__', '').startswith(base)
    if name == "__init__" or name == "__call__":
        return False
    return skip


def configure_builder(app):
    if 'latex' in app.builder.name:
        app.config.exclude_patterns.append('index.rst')
        app.config.master_doc = 'latex_index'
    else:
        app.config.exclude_patterns.append('latex_index.rst')


def setup(app):
    app.connect('builder-inited', configure_builder)
    app.connect("autodoc-skip-member", skip)
    app.add_css_file('theme_overrides.css')


# -- Options for modindex -----------------------------------------------
modindex_common_prefix = ['mushroom_rl.']

# -- Options for autosummary -----------------------------------------------

autosummary_generate = False


# -- Options for intersphinx ---------------------------------------------------

intersphinx_mapping = {
    "torch": ("https://docs.pytorch.org/docs/stable/", None)
}
