# -*- coding: utf-8 -*-
#
# Mushroom documentation build configuration file, created by
# sphinx-quickstart on Wed Dec  6 10:51:04 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

##from mushroom_rl import __version__


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.

import os
import sys
sys.path.insert(0, os.path.abspath('.'))

#from mushroom_rl import __version__

# General information about the project.
project = u'MushroomRL'
copyright = u'2018-2021 Carlo D\'Eramo, Davide Tateo'
author = u'Carlo D\'Eramo'
# -- General configuration ------------------------------------------------

extensions = [
    "sphinx.ext.napoleon",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.todo",
    "numpydoc",
    "sphinx_togglebutton",
    'sphinx.ext.doctest',
    "sphinx.ext.githubpages",

]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "**.ipynb_checkpoints"]


# specifying the natural language populates some key tags
language = "en"

# -- Options for HTML output -------------------------------------------------

html_theme = "pydata_sphinx_theme"
html_logo = "_static/dark.png"

html_favicon = "_static/dark.png"
html_sourcelink_suffix = ""
html_last_updated_fmt = ""  # to reveal the build date in the pages meta



# Napoleon settings
napoleon_use_ivar = True
napoleon_use_admonition_for_references = True
# See https://github.com/sphinx-doc/sphinx/issues/9119
napoleon_custom_sections = [("Returns", "params_style")]


numpydoc_class_members_toctree = False

html_theme_options = {
    "external_links": [
        
        
         {
            "url": "https://groups.google.com/g/rl-list/c/v2FOgy0z9nc",
            "name": "Google groups",
        },
        {
            "url": "https://arxiv.org/abs/2001.01102",
            "name": "arxiv",
        },
        {
            "url": "https://www.jmlr.org/",
            "name": "Journal of Machine Learning Research",
        },
     
    ],
    "header_links_before_dropdown": 4,
    "icon_links": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/Mushroom_RL",
            "icon": "fa-brands fa-twitter",
        },
        {
            "name": "GitHub",
            "url": "https://github.com/MushroomRL/mushroom-rl",
            "icon": "fa-brands fa-github",
        },
        {
            "name": "PyPI",
            "url": "https://pypi.org/project/mushroom-rl/",
            "icon": "fa-custom fa-pypi",
        },
        {
            "name": "MushroomRL",
            "url": "https://github.com/MushroomRL/mushroom-rl",
            "icon": "_static/dark.png",
            "type": "local",
            "attributes": {"target": "_blank"},
        },
    ],
    # alternative way to set twitter and github header icons
    ##"github_url": "https://github.com/pydata/pydata-sphinx-theme",
    ##"twitter_url": "https://twitter.com/PyData",
    "logo": {
        "text": "MushroomRL",
        
        
    },
    ##"use_edit_page_button": True,
    "show_toc_level": 1,
    "navbar_align": "content",  # [left, content, right] For testing that the navbar items align properly
     "show_nav_level": 2,
    ##"announcement": "https://raw.githubusercontent.com/pydata/pydata-sphinx-theme/main/docs/_templates/custom-template.html",
    ##"show_version_warning_banner": True,
    ##"navbar_center": ["version-switcher", "navbar-nav"],
    # "navbar_start": ["navbar-logo"],
    # "navbar_end": ["theme-switcher", "navbar-icon-links"],
    # "navbar_persistent": ["search-button"],
    # "primary_sidebar_end": ["custom-template", "sidebar-ethical-ads"],
    # "article_footer_items": ["test", "test"],
    # "content_footer_items": ["test", "test"],
    "footer_start": ["copyright"],
    "footer_center": ["sphinx-version"],
    }
    
    
    
    
   
   
    


html_context = {
    "github_repo": "pydata-sphinx-theme",
    "github_version": "main",
    "doc_path": "docs",
}

# The master toctree document.
master_doc = 'index'
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = ["style.css"]
html_js_files = ["custom-icon.js"]
todo_include_todos = True


# -- application setup -------------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',

}
# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'MushroomRL.tex', u'MushroomRL Documentation',
     u'Carlo D\'Eramo, Davide Tateo', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
main_pages = [
    (master_doc, '/mushroom_rl', u'MushroomRL Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'MushroomRL', u'MushroomRL Documentation',
     author, 'MushroomRL', 'One line description of project.',
     'Miscellaneous'),
]



# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Options for autodoc ---------------------------------------------------

autodoc_member_order = 'bysource'
autodoc_mock_imports = ['torch', 'pybullet', 'pybullet_data', 'pybullet_utils', 'dm_control', 'mujoco', 'glfw',
                        'habitat', 'habitat_baselines', 'habitat_sim', 'igibson',
                        'gym_minigrid']
add_module_names = False

def skip(app, what, name, obj, skip, options):
    if name == "__init__" or name == "__call__":
        return False
    return skip


