# This workflow will install Python dependencies, run tests and lint with a single version of Python, upload the coverage results to code climate

name: Test Pull Request

on:
  pull_request:
    branches: [ dev ] 


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        pip install -e .[all]
        sudo apt install unrar
    - name: Install Atari ROMs
      run: |
        wget http://www.atarimania.com/roms/Roms.rar 
        unrar x  -o+  Roms.rar
        ale-import-roms ./ROMS
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
 
