from mushroom_rl.environments.pybullet_envs.air_hockey.planar.env_hitting import AirHockeyPlanarHit
from mushroom_rl.environments.pybullet_envs.air_hockey.planar.env_defense import AirHockeyPlanarDefense

AirHockeyPlanarHit.register()
AirHockeyPlanarDefense.register()
